SET search_path = integrations, public;

DROP INDEX IF EXISTS geomag_sites_external_id_idx;
DROP INDEX IF EXISTS geomag_sites_last_updated_idx;
DROP INDEX IF EXISTS geomag_sites_geometry_idx;
DROP INDEX IF EXISTS geomag_units_unit_id_idx;
DROP INDEX IF EXISTS geomag_units_strat_name_id_idx;

DROP TABLE IF EXISTS geomag_units;
DROP TABLE IF EXISTS geomag_sites;

create table geomag_sites
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id integer not null,
    site_name varchar(255) not null,
    lat numeric(8, 5) default NULL::numeric,
    lng numeric(8, 5) default NULL::numeric,
    age_low numeric(10, 4) default NULL::numeric,
    age_high numeric(10, 4) default NULL::numeric,
    age numeric(10, 4) default NULL::numeric,
    age_unit varchar(10) default NULL::character varying,
    lithologies varchar(255) default NULL::character varying,
    formation varchar(255) default NULL::character varying,
    dir_polarity varchar(5),
    dir_inc numeric(10, 4),
    dir_dec numeric(10, 4),
    dir_alpha95 numeric(10, 4),
    dir_k numeric(12, 4),
    dir_n_specimens_lines numeric(10, 4),
    dir_tilt_correction numeric(10, 4),
    vgp_lat numeric(10, 4),
    vgp_lon numeric(10, 4),
    last_updated timestamptz   default NULL,
    created_at timestamptz   default now(),
    citations varchar(255) default null,
    geometry geometry(Point, 4326)
);
ALTER TABLE geomag_sites
    ADD CONSTRAINT geomag_sites_external_site_key
    UNIQUE (external_id, site_name);
alter table geomag_sites
    owner to "macrostrat-admin";
create index geomag_sites_external_id_idx on geomag_sites (external_id);
create index geomag_sites_last_updated_idx on geomag_sites (last_updated);
create index geomag_sites_geometry_idx on geomag_sites using gist (geometry);


create table geomag_units
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geomag_site_id integer not null references geomag_sites (id) on delete cascade,
    unit_id integer not null references macrostrat.units,
    strat_name_id integer references macrostrat.strat_names,
    strat_name varchar references macrostrat.strat_names,
    match_basis varchar(20) not null
);
--match_basis precedence is col.id (map unit) -> [lithology, age, formation name] info box to render this info if no match
--add nearest col function
--look at postgrest routes sgp, paleomag data, weaver schema/route, fossils, measures/measuremeta, integrations.dataset strabo data and see if we can serve a single data structure from same routes?
--create a standardize route and figure out how to unify all of the tables. run CRUD ops on this standardized table. can add a json data column.
alter table geomag_units owner to "macrostrat-admin";

create index geomag_units_unit_id_idx on geomag_units (unit_id);
create index geomag_units_strat_name_id_idx on geomag_units (strat_name_id);