SET search_path = integrations, public;

DROP INDEX IF EXISTS paleomag_sites_external_id_idx;
DROP INDEX IF EXISTS paleomag_sites_last_updated_idx;
DROP INDEX IF EXISTS paleomag_sites_geometry_idx;
DROP INDEX IF EXISTS unit_paleomag_unit_id_idx;
DROP INDEX IF EXISTS unit_paleomag_strat_name_id_idx;

DROP TABLE IF EXISTS unit_paleomag;
DROP TABLE IF EXISTS paleomag_sites;

create table paleomag_sites
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id integer not null,
    site_name varchar(255) not null,
    lat numeric(8, 5) default NULL::numeric,
    lng numeric(8, 5) default NULL::numeric,
    age_low numeric(10, 4) default NULL::numeric,
    age_high numeric(10, 4) default NULL::numeric,
    age_unit varchar(10) default NULL::character varying,
    lithologies varchar(255) default NULL::character varying,
    formation varchar(255) default NULL::character varying,
    dir_polarity varchar(5),
    dir_inc numeric(10, 4),
    dir_dec numeric(10, 4),
    dir_alpha95 numeric(10, 4),
    dir_k numeric(12, 4),
    dir_n_specimens_lines numeric(10, 4),
    dir_tilt_correction numeric(10, 4),
    vgp_lat numeric(10, 4),
    vgp_lon numeric(10, 4),
    last_updated timestamptz   default NULL,
    created_at timestamptz   default now(),
    citations varchar(255) default null,
    geometry geometry(Point, 4326)
);
ALTER TABLE paleomag_sites
    ADD CONSTRAINT paleomag_sites_external_site_key
    UNIQUE (external_id, site_name);
alter table paleomag_sites
    owner to "macrostrat-admin";
create index paleomag_sites_external_id_idx on paleomag_sites (external_id);
create index paleomag_sites_last_updated_idx on paleomag_sites (last_updated);
create index paleomag_sites_geometry_idx on paleomag_sites using gist (geometry);


create table unit_paleomag
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paleomag_site_id integer not null references paleomag_sites (id) on delete cascade,
    unit_id integer not null,
    strat_name_id integer default NULL,
    match_basis varchar(20) not null
);

alter table unit_paleomag owner to "macrostrat-admin";

create index unit_paleomag_unit_id_idx on unit_paleomag (unit_id);
create index unit_paleomag_strat_name_id_idx on unit_paleomag (strat_name_id);