-- this SQL must be executed on macrostrat before macrostrat_import_2.5.py can be successfully run

DROP VIEW macrostrat_api.col_ref_expanded;
DROP VIEW macrostrat_api.col_sections;
ALTER TABLE macrostrat.cols ALTER COLUMN col_name TYPE character varying;

CREATE VIEW macrostrat_api.col_sections AS  SELECT c.id AS col_id,
    c.col_name,
    u.section_id,
    u.position_top,
    u.position_bottom,
    fo.interval_name AS bottom,
    lo.interval_name AS top
   FROM macrostrat.cols c
     LEFT JOIN macrostrat.units u ON u.col_id = c.id
     LEFT JOIN macrostrat.intervals fo ON u.fo = fo.id
     LEFT JOIN macrostrat.intervals lo ON u.lo = lo.id;
     
CREATE VIEW macrostrat_api.col_ref_expanded AS  SELECT c.id AS col_id,
    c.col_name,
    c.col AS col_number,
    ''::text AS notes,
    c.lat,
    c.lng,
    json_build_object('id', r.id, 'pub_year', r.pub_year, 'author', r.author, 'ref', r.ref, 'doi', r.doi, 'url', r.url) AS ref
   FROM macrostrat.cols c
     LEFT JOIN macrostrat.col_refs cr ON c.id = cr.col_id
     LEFT JOIN macrostrat.refs r ON cr.ref_id = r.id;


-- remove NOT NULL from sections.fo_h and sections.lo_h
ALTER TABLE macrostrat.sections ALTER COLUMN fo_h DROP NOT NULL;
ALTER TABLE macrostrat.sections ALTER COLUMN lo_h DROP NOT NULL;

-- remove NOT NULL from units.max_thick, units.min_thick
ALTER TABLE macrostrat.units ALTER COLUMN max_thick DROP NOT NULL;
ALTER TABLE macrostrat.units ALTER COLUMN min_thick DROP NOT NULL;

-- remove NOT NULL from units.fo_h, units.lo_h, remove default
ALTER TABLE macrostrat.units ALTER COLUMN fo_h DROP NOT NULL;
ALTER TABLE macrostrat.units ALTER COLUMN lo_h DROP NOT NULL;
ALTER TABLE macrostrat.units ALTER COLUMN lo_h DROP DEFAULT;
ALTER TABLE macrostrat.units ALTER COLUMN fo_h DROP DEFAULT;

-- remove foreign key constraint on units.section_id
ALTER TABLE macrostrat.units DROP CONSTRAINT units_sections_fk;

-- units_sections autoincrement primary key was wonky, had to change in order to insert to: macrostrat.units_sections_id_seq
ALTER TABLE "macrostrat"."units_sections" ALTER COLUMN "id" SET DEFAULT nextval('macrostrat.units_sections_id_seq'::regclass);

-- remove null constraint on obsolete field
ALTER TABLE "macrostrat"."strat_names"
  ALTER COLUMN "old_id" DROP NOT NULL,
  ALTER COLUMN "old_strat_name_id" DROP NOT NULL,
  ALTER COLUMN "orig_id" DROP NOT NULL;
  
-- autoincrement primary key was wonky, had to change to insert into macrostrat.strat_names
ALTER TABLE "macrostrat"."strat_names" ALTER COLUMN "id" SET DEFAULT nextval('macrostrat.strat_names_id_seq'::regclass);

-- strat_tree did not have primary autoincrement key
ALTER TABLE "macrostrat"."strat_tree" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE macrostrat.strat_tree ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE macrostrat.strat_tree ADD CONSTRAINT strat_tree_pkey PRIMARY KEY(id);