version: "3"
services:
  gateway:
    image: jonasal/nginx-certbot:3
    ports:
      - "80:80"
      - "443:443"
    expose: [80, 443]
    environment:
      - CERTBOT_EMAIL
    volumes:
      - ./conf.d:/etc/nginx/user_conf.d:ro
      - nginx_secrets:/etc/letsencrypt
  web:
    image: ghcr.io/uw-macrostrat/web:develop
    restart: always
    expose: [80]
  mariadb:
    # The MariaDB service is Macrostrat's current database service.
    # Eventually this will be removed from the active configuration
    # or relegated to a 'legacy' profile. But for now, we need it at least
    # for continuity purposes.
    image: mariadb:10.10
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - /data/macrostrat/database-clusters/mariadb:/var/lib/mysql
    restart: always
  postgres:
    # Macrostrat's newer database clusters are based around PostgreSQL.
    # This should hopefully handle most of our databases going forward.
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
      # The name of the superuser
      - POSTGRES_USER
    volumes:
      - /data/macrostrat/database-clusters/postgres:/var/lib/postgresql/data
    restart: always
  tileserver:
    # Local registry for the tileserver image
    image: next.macrostrat.org:5000/macrostrat/tileserver:dev
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/macrostrat_v2
      - FORWARDED_ALLOW_IPS=*
    expose: [8000]
    command: >
      uvicorn
        --host 0.0.0.0
        --port 8000
        --log-level debug
        --proxy-headers
        macrostrat_tileserver.main:app
volumes:
  nginx_secrets:
