#
# Paleobiology Database environment customizations
# 
# This file can be modified in order to customize for this particular installation the behavior of
# the Paleobiology Database control and setup command 'pbdb', and other associated commands and
# scripts.
# 
# This file is completely separate from the docker and docker-compose configuration files.
# 


# The options that can be used in this file are specified below, in most cases with their default
# values. To change any of them, uncomment the line(s) and modify the values as desired. By
# default, the backup operation will use the API username and password. You can override this
# using the backup_user: and backup_password: options.

# file_permissions:
# devel_configuration: 
# project_choice: 
# include_paleobiodb: 
# include_macrostrat: 
# include_earthlife: 
# include_rockd: 
# include_mibasin: 

# site_paleobiodb: 
# site_macrostrat: 
# site_earthlife: 
# site_rockd: 
# site_mibasin: 

# pbdb_domain: 
# macro_domain: 
# earthlife_domain: 
# other_domain: 

# website_paleobiodb: 
# website_macrostrat: 
# website_earthlife: 
# website_rockd: 
# website_mibasin: 
# website_hostname: 
# website_other: 

# localsite_paleobiodb: 
# localsite_macrostrat: 
# localsite_earthlife: 
# localsite_rockd: 
# localsite_mibasin:

# nginx_workers: 
# pbapi_workers: 
# classic_workers: 
# earthlife_workers: 

# pbdb_remote: 'git@github.com/paleobiodb'
# macro_remote: 'git@github.com/UW-Macrostrat'
# pbdb_registry: 'registry.doit.wisc.edu/mmcclenn/paleobiodb-server'
# macro_registry: 'registry.doit.wisc.edu/mmcclenn/macrostrat-server'
# local_timezone: 
# letsencrypt_path: 
# unzip_cmd: 'gunzip -c'
# smtp_host: 'smtp.wiscmail.wisc.edu'
# smtp_port: '25'

# backup_dir: '/backups/daily'
# pbdb_default_load: 
# pbdb_master_login: 
# pbdb_master_host: 'paleobiodb.org'
# pbdb_proxy_host: 
# pbdb_master_backup_dir: '/backups/daily'
# pbdb_master_image_dir: '/var/paleobiodb/images'
# pbdb_master_archive_dir: '/var/paleobiodb/archives'
# pbdb_master_datalog_dir: '/var/paleobiodb/datalogs'
# pbdb_public_host: 
# macro_default_load: 
# macro_master_login: 
# macro_master_host: 'dev.macrostrat.org'
# macro_proxy_host: 
# macro_master_backup_dir: '/backup3'
# macro_public_host: 

# pbdb_username: 'pbdbuser'
# pbdb_password: 'pbdbpwd'
# macro_username: 'macrouser'
# macro_password: 'macropwd'
# exec_username: 'execuser'
# exec_password: 'execpwd'

# database_service: 'mariadb'
# postgres_service: 'postgres'
# webserver_service: 'nginx'

# ADDITIONAL SETTINGS:

