name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'CHANGES.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .["docs"]

      - name: Create API docs
        env:
          # we need to set a fake PG url or import will fail
          DATABASE_URL: postgresql://username:password@0.0.0.0:5439/postgis
        run: |
          pdocs as_markdown \
            --output_dir docs/src/api \
            --exclude_source \
            --overwrite \
            timvt.settings \
            timvt.layer \
            timvt.factory \
            timvt.dependencies \
            timvt.db \
            timvt.resources.enums \
            timvt.models.mapbox \
            timvt.models.OGC

      - name: Deploy docs
        run: mkdocs gh-deploy --force -f docs/mkdocs.yml
