/*
Move tileserver_stats.{day,location}_index into usage_stats, renamed with a
`tileserver_` prefix.

A rename in place, not a copy: the legacy lineage (new_system = false) predates
the log dumps and cannot be re-derived from any surviving source, so the tables
are moved with their data, indexes and constraints intact rather than rebuilt.

Safe to run in any order relative to the declarative `usage-stats` chunk, and
safe to re-run: each block no-ops once its work is done. If the chunk ran first
and created the destination tables empty, they are dropped and replaced by the
real ones -- but only after confirming they are in fact empty, so a populated
table is never silently discarded.

NOTE ON STYLE: this file deliberately contains no percent signs. Migrations are
executed through SQLAlchemy, whose driver reads a bare percent sign as a bind
parameter and fails with "incomplete placeholder". So dynamic SQL is built with
`||` and quote_ident() rather than format(), and messages are raised with
`USING MESSAGE =` rather than a format string. Doubling them up would work here
but breaks when the same file is run through psql, which does not.
*/

CREATE SCHEMA IF NOT EXISTS usage_stats;

DO $$
DECLARE
  src text;
  dst text;
  n_rows bigint;
  pair record;
BEGIN
  FOR pair IN
    SELECT *
    FROM (VALUES
      ('day_index', 'tileserver_day_index'),
      ('location_index', 'tileserver_location_index')
    ) AS t(old_name, new_name)
  LOOP
    src := 'tileserver_stats.' || quote_ident(pair.old_name);
    dst := 'usage_stats.' || quote_ident(pair.new_name);

    -- Nothing to do unless the source is a real table. It is absent on a fresh
    -- database, and a view once this migration has already run.
    CONTINUE WHEN to_regclass(src) IS NULL;
    CONTINUE WHEN (
      SELECT relkind FROM pg_class WHERE oid = src::regclass
    ) <> 'r';

    -- The destination may already exist, created empty by the declarative
    -- chunk. Drop it to make way for the real table -- but never if it holds
    -- rows, which would mean this is not the situation we think it is.
    IF to_regclass(dst) IS NOT NULL THEN
      EXECUTE 'SELECT count(*) FROM ' || dst INTO n_rows;
      IF n_rows > 0 THEN
        RAISE EXCEPTION USING MESSAGE =
          'Cannot migrate ' || src || ' -> ' || dst || ': destination already holds '
          || n_rows || ' rows. Resolve by hand; refusing to discard data.';
      END IF;
      EXECUTE 'DROP TABLE ' || dst;
    END IF;

    EXECUTE 'ALTER TABLE ' || src || ' SET SCHEMA usage_stats';
    EXECUTE 'ALTER TABLE usage_stats.' || quote_ident(pair.old_name)
      || ' RENAME TO ' || quote_ident(pair.new_name);

    RAISE NOTICE USING MESSAGE = 'Moved ' || src || ' -> ' || dst;
  END LOOP;
END
$$;

-- Bring constraint and index names in line with the renamed tables, so the
-- migrated schema matches what the declarative chunk would have built and
-- schema diffs stay quiet. Guarded individually: RENAME CONSTRAINT has no
-- IF EXISTS, and these are already correct on a freshly-built database.
DO $$
DECLARE
  pair record;
BEGIN
  FOR pair IN
    SELECT *
    FROM (VALUES
      ('tileserver_day_index', 'day_index_unique', 'tileserver_day_index_unique'),
      ('tileserver_location_index', 'location_index_unique', 'tileserver_location_index_unique')
    ) AS t(tbl, old_name, new_name)
  LOOP
    CONTINUE WHEN to_regclass('usage_stats.' || quote_ident(pair.tbl)) IS NULL;
    CONTINUE WHEN NOT EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE conrelid = ('usage_stats.' || quote_ident(pair.tbl))::regclass
        AND conname = pair.old_name
    );
    EXECUTE 'ALTER TABLE usage_stats.' || quote_ident(pair.tbl)
      || ' RENAME CONSTRAINT ' || quote_ident(pair.old_name)
      || ' TO ' || quote_ident(pair.new_name);
  END LOOP;
END
$$;

ALTER INDEX IF EXISTS usage_stats.location_index_zxy
  RENAME TO tileserver_location_index_zxy;

-- Restore the old names as views, so the tileserver heatmap route, the `plot`
-- command and ad-hoc queries keep working while consumers migrate. (The
-- declarative chunk defines these too; repeated here so this migration leaves
-- the database consistent on its own.)
CREATE OR REPLACE VIEW tileserver_stats.day_index AS
  SELECT * FROM usage_stats.tileserver_day_index;

CREATE OR REPLACE VIEW tileserver_stats.location_index AS
  SELECT * FROM usage_stats.tileserver_location_index;

/*
Reset the log-dump lineage, so the database is left ready for a clean re-capture.

processed_logs is an ingestion ledger, not data: it is fully regenerated by
re-capture, and its key changes to (object_name, pipeline), so it is dropped
rather than migrated.

Dropping the ledger on its own would be a trap, though. The aggregate upserts
accumulate (ON CONFLICT ... num_requests + EXCLUDED.num_requests), so an empty
ledger next to surviving new_system rows means the next `capture` re-ingests
every object and adds its counts on top of the ones already there -- silently
doubling five months of history. The ledger and the rows it accounts for have
to go together.

That is safe because the new_system lineage is exactly reproducible: the log
dumps run 2026-03-23 -> present with no gaps, and 2026-03-23 is also the first
new_system date -- logging and the dumps began together and nothing has been
rotated away. The legacy lineage (new_system = false, back to 2018) is NOT
reproducible and is deliberately left untouched.
*/
DROP TABLE IF EXISTS tileserver_stats.processed_logs;

DO $$
DECLARE
  n_day bigint;
  n_loc bigint;
BEGIN
  DELETE FROM usage_stats.tileserver_day_index WHERE new_system;
  GET DIAGNOSTICS n_day = ROW_COUNT;
  DELETE FROM usage_stats.tileserver_location_index WHERE new_system;
  GET DIAGNOSTICS n_loc = ROW_COUNT;
  RAISE NOTICE USING MESSAGE =
    'Cleared ' || n_day || ' day / ' || n_loc || ' location new-system rows; '
    || 're-run `macrostrat usage-stats capture` to rebuild.';
END
$$;
