CREATE SCHEMA IF NOT EXISTS integrations;

CREATE TABLE integrations.sgp_matches (
  sample_id integer PRIMARY KEY,
  match_set text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  original_num text,
  is_standard boolean,
  max_depth float,
  composite_height_m float,
  geom geometry(Point, 4326),
  interpreted_age text,
  interpreted_age_notes text,
  min_age numeric,
  max_age numeric,
  age_by text,
  data_source text,
  source_text text,
  col_id integer,
  count integer,
  strat_names text,
  match_strat_name_id integer,
  match_strat_name text,
  match_strat_name_clean text,
  match_rank text,
  match_parent_id integer,
  match_concept_id integer,
  match_unit_id integer,
  match_col_id integer,
  match_depth integer,
  match_basis text,
  match_spatial_basis text,
  match_min_age float,
  match_max_age float,
  match_mid_age float,
  match_age_span float,
  age_span_delta float,
  mid_age_delta float
);
