version: "3"
services:
  database:
    # PostgreSQL 13 is needed in order to allow force-dropping the database
    # (in testing mode)
    # docker pull imresamu/postgis:15-3.4
    image: ${PG_DATABASE_CONTAINER:-imresamu/postgis:15-3.4}
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      # This allows connections without a password, which is expedient but insecure...
      - POSTGRES_PASSWORD
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${MACROSTRAT_DB_PORT:-5432}:5432"
    expose:
      - 5432
    volumes:
      - db_cluster:/var/lib/postgresql/data
  mariadb:
    # The MariaDB service is Macrostrat's v1 database service.
    # This is currently being removed from the active configuration
    # and relegated to a 'legacy' profile. But for now, we need it
    # at least for inspection purposes.
    image: mariadb:10.10
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - mysql_cluster:/var/lib/mysql
    restart: always
volumes:
  db_cluster:
  mysql_cluster:
