version: "3"
services:
  database:
    # PostgreSQL 13 is needed in order to allow force-dropping the database
    # (in testing mode)
    # docker pull imresamu/postgis:15-3.4
    image: ${PG_DATABASE_CONTAINER:-imresamu/postgis:15-3.4}
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      # This allows connections without a password, which is expedient but insecure...
      - POSTGRES_PASSWORD
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${MACROSTRAT_DB_PORT:-5432}:5432"
    expose:
      - 5432
    volumes:
      - db_cluster:/var/lib/postgresql/data
  mariadb:
    # The MariaDB service is Macrostrat's v1 database service.
    # This is currently being removed from the active configuration
    # and relegated to a 'legacy' profile. But for now, we need it
    # at least for inspection purposes.
    image: mariadb:10.10
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - mysql_cluster:/var/lib/mysql
    restart: always
  postgrest:
    image: postgrest/postgrest:v12.0.2
    ports:
      - "3050:3000"
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - PGRST_DB_SCHEMA=macrostrat_api
      - PGRST_DB_ANON_ROLE=web_anon
      #- PGRST_SERVER_PROXY_URI=http://database:5432
      - PGRST_SERVER_PORT=3000
      - PGRST_SERVER_HOST=

  # Schema-only Test DB instance for applying migrations
  migrations-test-db:
    image: postgis-with-audit
    profiles: ['migrations-test']
    build:
      context: .
      dockerfile: ./postgis-audit.Dockerfile
    ports:
      - "${MACROSTRAT_DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=macrostrat
volumes:
  db_cluster:
  mysql_cluster:
