[tool.poetry]
authors = ["Daven Quinn <dev@davenquinn.com>"]
description = "Macrostrat tile server"
name = "macrostrat.tileserver"
packages = [
  {include = "macrostrat_tileserver"},
]
version = "2.0.1"

[tool.poetry.dependencies]
fastapi = "^0.92.0"
fastapi-utils = "^0.2.1"
"macrostrat.database" = "^2.0"
"macrostrat.utils" = "^1.1.0"
pytest = "^7.2.1"
python = "^3.8"
python-dotenv = "^1.0.0"
timvt = "0.7.0"
typer = "^0.9"
uvicorn = "0.16.0"

[tool.poetry.extras]
# Extra dependencies to compile raster tiles
raster_tiles = ["mapnik"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
tileserver = "macrostrat_tileserver.cli:_cli"
