[tool.poetry]
authors = ["Daven Quinn <dev@davenquinn.com>"]
description = "Macrostrat tile server"
name = "macrostrat_tileserver"
packages = [
  {include = "macrostrat_tileserver"},
]
version = "2.0.0"

[tool.poetry.dependencies]
fastapi = "*"
"macrostrat.database" = "^1.0.2"
python = "^3.8"
timvt = "0.7.0"
typer = "^0.4.2"
uvicorn = "0.16.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
tileserver = "macrostrat_tileserver.cli:app"
