/*
Get the map face that defines a polygon for a specific topology
*/
CREATE OR REPLACE FUNCTION map_bounds_topology.identity_for_area(
  geom geometry,
  _map_layer integer
)
  RETURNS integer AS $$
/** The candidate set is every map with a `map_priority` row for this layer.
  For a composite layer those rows are generated by `sync-priority-paths`, which
  is what lets a composite layer be solved like any other instead of being filled
  by copying its members' faces. The `coalesce` keeps the function working on a
  database whose paths have not been synced yet, by falling back to the scalar. */
SELECT mc.source_id
FROM map_bounds.map_area ma
JOIN map_bounds.map_priority mc
  ON mc.source_id = ma.source_id
 AND mc.map_layer = _map_layer
-- The center of the area must be within each candidate map
WHERE ST_Intersects(ST_PointOnSurface(geom), ma.geometry)
  -- A virtual compilation has a boundary but no content, so it is never an
  -- answer: the flattening descends through it to whichever member has the
  -- geometry, and this keeps the compilation itself out of the running. A
  -- mosaic member placed in the layer *is* an answer: it holds no polygons but
  -- stands for its parent's inside its footprint.
  AND map_bounds.has_content(mc.source_id)
ORDER BY
  mc.priority_path DESC,
  ma.area_km -- smaller areas first
LIMIT 1;
$$ LANGUAGE sql;


/** TODO: this has to be recreated here because the types are wrong **/
CREATE OR REPLACE FUNCTION map_bounds_topology.identity_for_face(face_id integer, map_layer integer)
  RETURNS integer AS $$
SELECT mc.source_id
FROM map_bounds_topology.relation r
JOIN map_bounds.map_area f
  -- A topogeometry id is only unique *within* a layer, so both halves are
  -- needed: `map_face` topogeometries live in a different layer and would
  -- otherwise collide with `map_area` ones by id alone.
  ON (f.topo).id = r.topogeo_id
 AND (f.topo).layer_id = r.layer_id
JOIN map_bounds.map_priority mc
  ON mc.source_id = f.source_id
 AND mc.map_layer = $2
WHERE element_id = $1
  AND element_type = 3
  AND map_bounds.has_content(mc.source_id)
ORDER BY
  mc.priority_path DESC,
  f.area_km -- smaller areas first
LIMIT 1;
$$ LANGUAGE SQL IMMUTABLE;

/** The set-oriented form of `identity_for_face`, for a whole layer at once.

  Must agree with `identity_for_face` exactly -- same candidate set, same ordering,
  same `has_content` exclusion -- because the dissolve uses whichever is
  available and the two must not disagree about which map owns a face. `DISTINCT ON`
  is the bulk equivalent of that function's `LIMIT 1`.

  Identity is returned as text so the library can hold it without knowing the
  strategy's key type; joinability only ever tests equality.
*/
CREATE OR REPLACE FUNCTION map_bounds_topology.resolve_layer_identity(_map_layer integer)
  RETURNS TABLE (face_id integer, identity text) AS $$
SELECT DISTINCT ON (r.element_id)
  r.element_id,
  mc.source_id::text
FROM map_bounds_topology.relation r
JOIN map_bounds.map_area f
  ON (f.topo).id = r.topogeo_id
 AND (f.topo).layer_id = r.layer_id
JOIN map_bounds.map_priority mc
  ON mc.source_id = f.source_id
 AND mc.map_layer = _map_layer
WHERE r.element_type = 3
  AND map_bounds.has_content(mc.source_id)
ORDER BY r.element_id, mc.priority_path DESC, f.area_km;
$$ LANGUAGE SQL STABLE;


CREATE OR REPLACE FUNCTION map_bounds_topology.faces_are_joinable(f1 integer, f2 integer, map_layer integer)
  RETURNS boolean AS $$
DECLARE
  id1 integer;
  id2 integer;
BEGIN
  id1 := map_bounds_topology.identity_for_face(f1, map_layer);
  id2 := map_bounds_topology.identity_for_face(f2, map_layer);
  RETURN id1 IS NOT DISTINCT FROM id2;
END
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION {topo_schema}.map_face_is_identified(map_face {topo_schema}.map_face)
  RETURNS boolean AS $$
BEGIN
  RETURN map_face.map_id IS NOT NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
