CREATE SCHEMA IF NOT EXISTS text_vectors;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS text_vectors.search_vector (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text text NOT NULL,
    model_name text NOT NULL,
    model_version text NOT NULL,
    text_vector vector NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE (text, model_name)
);

CREATE OR REPLACE FUNCTION text_vectors.distance(
  text_vector vector,
  search_vector vector
) RETURNS float
AS $$
BEGIN
  RETURN 1 - (text_vector <=> search_vector);
END;
$$
LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION text_vectors.norm_distance(
  text_vector vector,
  search_vector vector
) RETURNS float
AS $$
BEGIN
  RETURN -(text_vector <#> search_vector);
END;
$$ LANGUAGE plpgsql;

TRUNCATE TABLE text_vectors.search_vector;
