
-- 2026-07-06 23:32:18
-- Environment: local
-- 125 changes applied (23 unsafe)
-- 67 statements were not logged

DROP TRIGGER IF EXISTS "relation_integrity_checks"
    ON "map_bounds_topology"."relation";
ALTER TABLE "map_bounds"."map_area" DROP
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "map_bounds"."map_topo" DROP
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "map_bounds_topology"."map_face" DROP
CONSTRAINT "check_topogeom_topo";
DROP
FUNCTION IF EXISTS "map_bounds"."antimeridian_fix"(geometry, integer);
DROP
FUNCTION IF EXISTS "map_bounds"."fix_antimeridian"(geometry);
DROP
FUNCTION IF EXISTS "map_bounds"."update_rgeom_basic"(geometry);
DROP
FUNCTION IF EXISTS "map_bounds_topology"."dissolve_groups"(_map_layer integer, _barrier_layers integer[]);
DROP
FUNCTION IF EXISTS "map_ingestion_api"."grouped_query"(_table_name text, _group_by_columns text[]);
DROP
FUNCTION IF EXISTS "public"."aggregate_if_small"(state anyarray);
DROP
FUNCTION IF EXISTS "public"."collect_unique_values"(state anyarray, next_val anyelement);
ALTER TABLE "storage"."objects" DROP
CONSTRAINT "object_pkey";
ALTER TABLE "tileserver_stats"."requests" DROP
CONSTRAINT "requests_pkey";
DROP TABLE "tileserver_stats"."processing_status";
DROP TABLE "tileserver_stats"."requests";
CREATE TABLE "maps"."line_type" ("id" text NOT NULL, "description" text);
CREATE TABLE "maps"."point_type" ("id" text NOT NULL, "description" text);
CREATE TABLE "maps_metadata"."ingest_state" ("id" text NOT NULL, "description" text, "color" CHARACTER varying(25));
ALTER TABLE "macrostrat"."cols" ALTER COLUMN "col_name"
   SET DATA TYPE text USING "col_name"::text;
ALTER TABLE "macrostrat"."intervals" ALTER COLUMN "orig_color" DROP NOT NULL;
ALTER TABLE "macrostrat"."sections" ALTER COLUMN "fo_h" DROP NOT NULL;
ALTER TABLE "macrostrat"."sections" ALTER COLUMN "lo_h" DROP NOT NULL;
ALTER TABLE "macrostrat"."strat_names" ALTER COLUMN "old_id" DROP NOT NULL;
ALTER TABLE "macrostrat"."strat_names" ALTER COLUMN "old_strat_name_id" DROP NOT NULL;
ALTER TABLE "macrostrat"."strat_names" ALTER COLUMN "orig_id" DROP NOT NULL;
ALTER TABLE "macrostrat"."strat_tree" ALTER COLUMN "id"
   SET NOT NULL;
ALTER TABLE "macrostrat"."strat_tree" ALTER COLUMN "id" ADD GENERATED always AS IDENTITY;
ALTER TABLE "maps_metadata"."ingest_process" ALTER COLUMN "source_id"
   SET NOT NULL;
ALTER TABLE "maps_metadata"."ingest_process" ALTER COLUMN "state"
   SET DATA TYPE text USING "state"::text;
ALTER TABLE "storage"."objects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
DROP SEQUENCE IF EXISTS "storage"."object_id_seq";
DROP SEQUENCE IF EXISTS "tileserver_stats"."requests_req_id_seq";
DROP TYPE "maps"."ingest_state";
CREATE UNIQUE INDEX strat_tree_pkey
    ON macrostrat.strat_tree USING btree (id);
CREATE UNIQUE INDEX line_type_pkey
    ON maps.line_type USING btree (id);
CREATE UNIQUE INDEX point_type_pkey
    ON maps.point_type USING btree (id);
CREATE UNIQUE INDEX ingest_process_source_id_unique
    ON maps_metadata.ingest_process USING btree (source_id);
CREATE UNIQUE INDEX ingest_state_pkey
    ON maps_metadata.ingest_state USING btree (id);
CREATE UNIQUE INDEX objects_pkey
    ON storage.objects USING btree (id);
ALTER TABLE "macrostrat"."strat_tree" ADD
CONSTRAINT "strat_tree_pkey" PRIMARY KEY USING INDEX "strat_tree_pkey";
ALTER TABLE "maps"."line_type" ADD
CONSTRAINT "line_type_pkey" PRIMARY KEY USING INDEX "line_type_pkey";
ALTER TABLE "maps"."point_type" ADD
CONSTRAINT "point_type_pkey" PRIMARY KEY USING INDEX "point_type_pkey";
ALTER TABLE "maps_metadata"."ingest_state" ADD
CONSTRAINT "ingest_state_pkey" PRIMARY KEY USING INDEX "ingest_state_pkey";
ALTER TABLE "storage"."objects" ADD
CONSTRAINT "objects_pkey" PRIMARY KEY USING INDEX "objects_pkey";
ALTER TABLE "macrostrat"."unit_boundaries" ADD
CONSTRAINT "unit_boundaries_check" CHECK (((unit_id IS NOT NULL) OR (unit_id_2 IS NOT NULL))) NOT VALID;
ALTER TABLE "macrostrat"."unit_boundaries" VALIDATE
CONSTRAINT "unit_boundaries_check";
ALTER TABLE "maps_metadata"."ingest_process" ADD
CONSTRAINT "ingest_process_slug_fkey"
FOREIGN KEY (slug) REFERENCES maps.sources(slug) NOT VALID;
ALTER TABLE "maps_metadata"."ingest_process" VALIDATE
CONSTRAINT "ingest_process_slug_fkey";
ALTER TABLE "maps_metadata"."ingest_process" ADD
CONSTRAINT "ingest_process_source_id_unique" UNIQUE USING INDEX "ingest_process_source_id_unique";
ALTER TABLE "maps_metadata"."ingest_process" ADD
CONSTRAINT "ingest_process_state_fkey"
FOREIGN KEY (state) REFERENCES maps_metadata.ingest_state(id) NOT VALID;
ALTER TABLE "maps_metadata"."ingest_process" VALIDATE
CONSTRAINT "ingest_process_state_fkey";
ALTER TABLE "map_bounds"."map_area" ADD
CONSTRAINT "check_topogeom_topo" CHECK ((((topo).topology_id = 1) AND ((topo).layer_id = 2) AND ((topo).type = 3))) NOT VALID;
ALTER TABLE "map_bounds"."map_area" VALIDATE
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "map_bounds"."map_topo" ADD
CONSTRAINT "check_topogeom_topo" CHECK ((((topo).topology_id = 1) AND ((topo).layer_id = 3) AND ((topo).type = 3))) NOT VALID;
ALTER TABLE "map_bounds"."map_topo" VALIDATE
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "map_bounds_topology"."map_face" ADD
CONSTRAINT "check_topogeom_topo" CHECK ((((topo).topology_id = 1) AND ((topo).layer_id = 1) AND ((topo).type = 3))) NOT VALID;
ALTER TABLE "map_bounds_topology"."map_face" VALIDATE
CONSTRAINT "check_topogeom_topo";
CREATE TRIGGER relation_integrity_checks
BEFORE INSERT
    OR UPDATE
    ON map_bounds_topology.relation
   FOR EACH ROW EXECUTE
FUNCTION relationtrigger('1', 'map_bounds_topology')


-- 2026-07-06 23:33:25
-- Environment: local
-- 18 changes applied (6 unsafe)
-- 1 statements were not logged

ALTER TABLE "map_bounds"."map_area" DROP
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "map_bounds"."map_topo" DROP
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "map_bounds_topology"."map_face" DROP
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "maps_metadata"."ingest_process" DROP
CONSTRAINT "ingest_process_state_fkey";
DROP
FUNCTION IF EXISTS "public"."aggregate_if_small"(state anyarray);
DROP
FUNCTION IF EXISTS "public"."collect_unique_values"(state anyarray, next_val anyelement);
ALTER TABLE "maps_metadata"."ingest_process" ALTER COLUMN "source_id"
   SET NOT NULL;
CREATE UNIQUE INDEX ingest_process_source_id_unique
    ON maps_metadata.ingest_process USING btree (source_id);
ALTER TABLE "maps_metadata"."ingest_process" ADD
CONSTRAINT "ingest_process_source_id_unique" UNIQUE USING INDEX "ingest_process_source_id_unique";
ALTER TABLE "map_bounds"."map_area" ADD
CONSTRAINT "check_topogeom_topo" CHECK ((((topo).topology_id = 1) AND ((topo).layer_id = 2) AND ((topo).type = 3))) NOT VALID;
ALTER TABLE "map_bounds"."map_area" VALIDATE
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "map_bounds"."map_topo" ADD
CONSTRAINT "check_topogeom_topo" CHECK ((((topo).topology_id = 1) AND ((topo).layer_id = 3) AND ((topo).type = 3))) NOT VALID;
ALTER TABLE "map_bounds"."map_topo" VALIDATE
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "map_bounds_topology"."map_face" ADD
CONSTRAINT "check_topogeom_topo" CHECK ((((topo).topology_id = 1) AND ((topo).layer_id = 1) AND ((topo).type = 3))) NOT VALID;
ALTER TABLE "map_bounds_topology"."map_face" VALIDATE
CONSTRAINT "check_topogeom_topo";
ALTER TABLE "maps_metadata"."ingest_process" ADD
CONSTRAINT "ingest_process_state_fkey"
FOREIGN KEY (state) REFERENCES maps_metadata.ingest_state(id) NOT VALID;
ALTER TABLE "maps_metadata"."ingest_process" VALIDATE
CONSTRAINT "ingest_process_state_fkey";

