--
-- PostgreSQL database dump
--

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg12+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: integrations; Type: SCHEMA; Schema: -; Owner: macrostrat-admin
--

CREATE SCHEMA integrations;


ALTER SCHEMA integrations OWNER TO "macrostrat-admin";

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dataset; Type: TABLE; Schema: integrations; Owner: macrostrat-admin
--

CREATE TABLE integrations.dataset (
    id integer NOT NULL,
    uid uuid NOT NULL,
    name text,
    url text,
    type integer NOT NULL,
    geom public.geometry(Point,4326) NOT NULL,
    symbol text,
    data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE integrations.dataset OWNER TO "macrostrat-admin";

--
-- Name: dataset_id_seq; Type: SEQUENCE; Schema: integrations; Owner: macrostrat-admin
--

ALTER TABLE integrations.dataset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME integrations.dataset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dataset_type; Type: TABLE; Schema: integrations; Owner: macrostrat-admin
--

CREATE TABLE integrations.dataset_type (
    id integer NOT NULL,
    name text NOT NULL,
    organization text NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE integrations.dataset_type OWNER TO "macrostrat-admin";

--
-- Name: dataset_type_id_seq; Type: SEQUENCE; Schema: integrations; Owner: macrostrat-admin
--

ALTER TABLE integrations.dataset_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME integrations.dataset_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sgp_analyses; Type: TABLE; Schema: integrations; Owner: macrostrat_admin
--

CREATE TABLE integrations.sgp_analyses (
    sample_id integer,
    original_num character varying(250),
    analyte_det_id integer,
    analyte_code character varying(200),
    abundance numeric(17,9),
    determination_unit character varying(10),
    exp_method_id integer,
    ana_method_id integer,
    reference_id integer
);


ALTER TABLE integrations.sgp_analyses OWNER TO macrostrat_admin;

--
-- Name: sgp_matches; Type: TABLE; Schema: integrations; Owner: macrostrat-admin
--

CREATE TABLE integrations.sgp_matches (
    sample_id integer NOT NULL,
    match_set text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    original_num text,
    is_standard boolean,
    max_depth double precision,
    composite_height_m double precision,
    geom public.geometry(Point,4326),
    interpreted_age text,
    interpreted_age_notes text,
    min_age numeric,
    max_age numeric,
    age_by text,
    data_source text,
    source_text text,
    col_id integer,
    count integer,
    strat_names text,
    match_strat_name_id integer,
    match_strat_name text,
    match_strat_name_clean text,
    match_rank text,
    match_parent_id integer,
    match_concept_id integer,
    match_unit_id integer,
    match_col_id integer,
    match_depth integer,
    match_basis text,
    match_spatial_basis text,
    match_min_age double precision,
    match_max_age double precision,
    match_mid_age double precision,
    match_age_span double precision,
    age_span_delta double precision,
    mid_age_delta double precision
);


ALTER TABLE integrations.sgp_matches OWNER TO "macrostrat-admin";

--
-- Name: sgp_samples; Type: TABLE; Schema: integrations; Owner: macrostrat_admin
--

CREATE TABLE integrations.sgp_samples (
    sample_id integer,
    igsn character varying(25),
    original_num character varying(250),
    is_standard boolean,
    min_depth numeric(8,3),
    max_depth numeric(8,3),
    height_depth_m numeric(7,2),
    composite_height_m numeric(9,2),
    geom public.geometry,
    verbatim_strat character varying(250),
    verbatim_lith character varying(4000),
    strat_notes character varying(250),
    coll_event_notes character varying(4000),
    url character varying(3000),
    data_source character varying(255),
    geol_context_id integer,
    lithostrat_id integer,
    coll_event_id integer,
    macrostrat_id integer
);


ALTER TABLE integrations.sgp_samples OWNER TO macrostrat_admin;

--
-- Name: dataset dataset_pkey; Type: CONSTRAINT; Schema: integrations; Owner: macrostrat-admin
--

ALTER TABLE ONLY integrations.dataset
    ADD CONSTRAINT dataset_pkey PRIMARY KEY (id);


--
-- Name: dataset_type dataset_type_name_organization_key; Type: CONSTRAINT; Schema: integrations; Owner: macrostrat-admin
--

ALTER TABLE ONLY integrations.dataset_type
    ADD CONSTRAINT dataset_type_name_organization_key UNIQUE (name, organization);


--
-- Name: dataset_type dataset_type_pkey; Type: CONSTRAINT; Schema: integrations; Owner: macrostrat-admin
--

ALTER TABLE ONLY integrations.dataset_type
    ADD CONSTRAINT dataset_type_pkey PRIMARY KEY (id);


--
-- Name: dataset dataset_uid_key; Type: CONSTRAINT; Schema: integrations; Owner: macrostrat-admin
--

ALTER TABLE ONLY integrations.dataset
    ADD CONSTRAINT dataset_uid_key UNIQUE (uid);


--
-- Name: sgp_matches sgp_matches_pkey; Type: CONSTRAINT; Schema: integrations; Owner: macrostrat-admin
--

ALTER TABLE ONLY integrations.sgp_matches
    ADD CONSTRAINT sgp_matches_pkey PRIMARY KEY (sample_id);


--
-- Name: dataset dataset_type_fkey; Type: FK CONSTRAINT; Schema: integrations; Owner: macrostrat-admin
--

ALTER TABLE ONLY integrations.dataset
    ADD CONSTRAINT dataset_type_fkey FOREIGN KEY (type) REFERENCES integrations.dataset_type(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

