
all:
	poetry run poetry run pip install beautifulsoup4
	poetry run poetry run pip install requests
	poetry run python /Users/afromandi/Macrostrat/Projects/macrostrat/map-staging/macrostrat/map_staging/japan-scraper.py