version: "3"
services:
  # DATABASE SERVICES
  mariadb:
    # The MariaDB service is Macrostrat's current database service.
    image: mariadb:10.7
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
  postgres:
    # Macrostrat's newer database clusters are based around PostgreSQL.
    # This should hopefully handle most of our databases going forward.
    image: postgis/postgis:14-3.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  api:
    # Macrostrat API
    build: services/macrostrat-api
    expose: [5000]
    ports:
      - "80:5000"
  cli:
    build: tools/macrostrat-utils
    environment:
      - MACROSTRAT_PG_DATABASE=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/burwell
      - MACROSTRAT_MYSQL_DATABASE=mysql://root:${MARIADB_ROOT_PASSWORD}@mariadb:3306/macrostrat
      - REDIS_PORT
      - TILE_CACHE_PATH
      - TILE_CACHE_PATH_VECTOR
      - TILESERVER_SECRET
      - MBTILES_PATH
  tileserver:
    build: services/tileserver
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/burwell
    ports:
      - "8000:8000"
volumes:
  mariadb_data:
  postgres_data: