version: "3"
services:
  gateway:
    image: jonasal/nginx-certbot:3
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL
    volumes:
      - ./system/nginx-config:/etc/nginx/user_conf.d:ro
      - nginx_secrets:/etc/letsencrypt
  homepage:
    # A markdown server for the homepage
    image: dannyben/madness
    expose: [3000]
    volumes:
      - ./docs:/docs:ro
  # DATABASE SERVICES
  mariadb:
    # The MariaDB service is Macrostrat's current database service.
    # Eventually this will be removed from the active configuration
    # or relegated to a 'legacy' profile
    image: mariadb:10.7
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
  postgres:
    # Macrostrat's newer database clusters are based around PostgreSQL.
    # This should hopefully handle most of our databases going forward.
    image: postgis/postgis:14-3.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  api:
    # Macrostrat API
    build: services/macrostrat-api
    expose: [5000]
  cli:
    build: tools/macrostrat-utils
    container_name: macrostrat-cli
    environment:
      - MACROSTRAT_PG_DATABASE=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/burwell
      - MACROSTRAT_MYSQL_DATABASE=mysql://root:${MARIADB_ROOT_PASSWORD}@mariadb:3306/macrostrat
      - REDIS_PORT
      - TILE_CACHE_PATH
      - TILE_CACHE_PATH_VECTOR
      - TILESERVER_SECRET
      - MBTILES_PATH
    volumes:
      - ./tools/macrostrat-utils:/code:ro
  tileserver:
    build: services/tileserver
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/burwell
      - FORWARDED_ALLOW_IPS=*
    expose: [8000]
    command: >
      uvicorn
        --host 0.0.0.0
        --port 8000
        --log-level debug
        --proxy-headers
        macrostrat_tileserver.main:app
  rockd_api:
    build: services/rockd-api/api
    expose: [5500]
    volumes:
      - /var/data/rockd:/var/data/rockd
  dacite:
    build:
      context: services/column-builder/dacite
      dockerfile: prod.Dockerfile
    environment:
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_CLIENT_URL=${NEXT_PUBLIC_CLIENT_URL}
    ports:
      - 1234:1234
    depends_on:
      - postgrest
  postgrest:
    image: postgrest/postgrest
    ports: 
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/column_data
      PGRST_DB_SCHEMA: macrostrat_api,weaver_api
      PGRST_DB_ANON_ROLE: postgres
      PGRST_SERVER_PORT: 3001
    depends_on:
      - postgres
  birdseye:
    build: services/column-builder/BirdsEye/frontend
    ports:
      - "1235:1235"
  geologic_map_server:
    build: services/column-builder/BirdsEye/backend
    environment:
      - GEOLOGIC_MAP_CONFIG=/app/docker-assets/docker-map-config.json
      - GEOLOGIC_MAP_DATABASE=${GEOLOGIC_MAP_DATABASE}
      - IMPORTER_API=${IMPORTER_API}
      - EXPORTER_API=${EXPORTER_API}
    entrypoint: "/python_app/docker-scripts/run"
    ports:
      - "40053:8000"
    depends_on:
      - postgres

volumes:
  mariadb_data:
  postgres_data:
  nginx_secrets:
