version: "3"
services:
  mariadb:
    image: mariadb:10.7
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
volumes:
  mariadb_data: