# This config file is empty for now but it serves as a placeholder for future
# configuration options, as well as informing the `macrostrat` command that
# this directory should be considered the root of a macrostrat system.
