- hosts: dev
  name: Remove Logical Volumes entirely (this deletes all data)
  become: true
  tasks:
    - name: Remove logical volume group 
      lvg:
        vg: macrostrat-data
        state: absent
        force: true