CREATE SCHEMA IF NOT EXISTS integrations;

CREATE TABLE IF NOT EXISTS integrations.dataset_type (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  organization text NOT NULL,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (name, organization)
);

CREATE TABLE IF NOT EXISTS integrations.dataset (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  uid uuid NOT NULL UNIQUE,
  name text,
  url text,
  type integer NOT NULL REFERENCES integrations.dataset_type(id) ON DELETE CASCADE,
  geom GEOMETRY(Point, 4326) NOT NULL,
  symbol text,
  data jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

-- Create a view to expose the integration datasets to the API
CREATE OR REPLACE VIEW macrostrat_api.dataset AS
  SELECT d.*,
        dt.name type_name,
        dt.organization
  FROM integrations.dataset d
  JOIN integrations.dataset_type dt ON d.type = dt.id;


CREATE OR REPLACE VIEW macrostrat_api.dataset_type AS
  SELECT * FROM integrations.dataset_type;
