name: Build Production

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+  # Semver Release

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hub.opensciencegrid.org/macrostrat/api-v3
          tags: |
            type=ref,event=pr,suffix=-{{date 'YYYYMMDDHHmmss'}}
            type=ref,event=branch,suffix=-{{date 'YYYYMMDDHHmmss'}}
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=sha-{{sha}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to OSG DockerHub
        uses: docker/login-action@v2
        with:
          registry: hub.opensciencegrid.org
          username: ${{ vars.HARBOR_CLI_NAME }}
          password: ${{ secrets.HARBOR_CLI_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
