version: "3"
services:
  database:
    image: postgis/postgis:13-3.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=topology
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
