[tool.poetry]
name = "usage-stats"
version = "0.1.0"
description = ""
authors = ["davidsklar99 <davidsklar99@outlook.com>"]
readme = "README.md"
packages = []  # ensures it's not treated as a package
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
requests = ">=2.32.4,<3.0.0"
asyncpg = ">=0.30.0,<0.31.0"
sqlalchemy = ">=2.0.41,<3.0.0"
psycopg2 = ">=2.9.10,<3.0.0"
asyncmy = ">=0.2.10,<0.3.0"
dotenv = ">=0.9.9,<0.10.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
