#!/usr/bin/env bash
# This script builds a docker image for a service.
# It should be run from the root of the repository.

# First, build local python modules

set -e

root=$(pwd)
dist_dir="py-modules/dist"

for module in $(ls -d py-modules/*/); do
  [ ! -f "$module/pyproject.toml" ] && continue
  if [ -d "$module" ]; then
    echo "Building $module"
    pushd "$module"
    poetry build --output $dist_dir
    popd
  fi
done


# Copy the dependencies to each relevant service

svc=services/legacy-tileserver

echo "Copying wheels"
mkdir -p $svc/deps
rm -f $svc/deps/*.whl
cp $dist_dir/*.whl $svc/deps

poetry --project=$svc lock

echo "Building Docker container $svc"
docker build $svc
