#!/usr/bin/env bash
# Prepare services for building docker containers

# First, build Python wheels for dependencies

set -e

function header() {
  echo -e "\n\033[1m$1\033[0m" >&2
}

root=$(pwd)
dist_dir="$root/py-modules/dist"

# First, build python wheels for dependencies
for module in $(ls -d py-modules/*/); do
  [ ! -f "$module/pyproject.toml" ] && continue
  if [ -d "$module" ]; then
    pushd $module 2>/dev/null
    header "Building module $(poetry version | cut -d' ' -f1)"
    poetry lock
    poetry build --output $dist_dir
    popd 2>/dev/null
  fi
done

# Then, copy dependency wheels into each service directory and lock dependencies

services=(
  "tileserver"
  "legacy-tileserver"
)

for service_name in "${services[@]}"; do
  # Check if the service directory exists
  header "Updating dependencies for service $service_name"
  pushd services/$service_name 2>/dev/null
  mkdir -p deps
  rm -f deps/*.whl
  cp $dist_dir/*.whl deps
  poetry lock
  popd 2>/dev/null
done
