#!/usr/bin/env bash
# Script to catch and tag releases of specific services, to stage them for CI pipelines.

set -e

services=(
  "tileserver"
  "legacy-tileserver"
  "usage-stats"
  "api-v3"
)

for service_name in "${services[@]}"; do
  # Lock dependencies
  pushd services/$service_name > /dev/null 2>&1
  uv lock
  popd > /dev/null 2>&1
done

# Fail if we are in a dirty state
if ! git diff-index --quiet HEAD --; then
  echo "Error: You have uncommitted changes. Please commit or stash them before running this script."
  exit 1
fi

for service_name in "${services[@]}"; do
  # Check if the service directory exists
  pushd services/$service_name > /dev/null 2>&1
  version=$(uv version --short)
  tag="$service_name-v$version"
  popd > /dev/null 2>&1

  # Check if the tag already exists
  if ! git rev-parse "$tag" >/dev/null 2>&1; then
    # Tag the image
    git tag "$tag" -m "Version $version of service $service_name"
    echo "Tagged service $service_name with version $version"
  fi
done
