
CREATE TABLE macrostrat.lookup_units_new (
  unit_id integer PRIMARY KEY NOT NULL,
  col_area numeric NOT NULL,
  project_id integer NOT NULL,
  t_int integer,
  t_int_name text,
  t_int_age numeric,
  t_age numeric,
  t_prop numeric,
  t_plat numeric,
  t_plng numeric,
  b_int integer,
  b_int_name text,
  b_int_age numeric,
  b_age numeric,
  b_prop numeric,
  b_plat numeric,
  b_plng numeric,
  clat numeric,
  clng numeric,
  color text,
  text_color text,
  units_above text,
  units_below text,
  pbdb_collections integer,
  pbdb_occurrences integer,
  age text,
  age_id integer,
  epoch text,
  epoch_id integer,
  period text,
  period_id integer,
  era text,
  era_id integer,
  eon text,
  eon_id integer
);

