#! /bin/bash

if [ $# -lt 2 ]
  then echo -e "Please provide a dataset name and a path to a shapefile. \n Usage: ./import dataset_name path/to/shapefile.shp\n You can optionally supply specify "
  exit 1
fi

APPEND=""
if [[ $3 == "true" ]];
  then APPEND="-a"
fi

ENCODING="UTF-8"
if [[ $4 != "" ]];
  then ENCODING=$4
fi

rm unprojected.* && ogr2ogr unprojected.shp -wrapdateline -t_srs "EPSG:4326" $2 && shp2pgsql -s 4326 $APPEND -W $ENCODING unprojected.shp sources.$1 | psql -h localhost -d burwell && rm unprojected.*
