#!/usr/bin/env bash 
# Run in this script's virtual environment
# Get Poetry's virtual environment path
poetry env info --path > /dev/null 2>&1
if [ $? -eq 0 ]; then
  VENV_PATH=$(poetry env info --path)
  export PATH=$VENV_PATH/bin:$PATH
  macrostrat $@
else
  echo "Could not find Poetry's virtual environment path."
  exit 1
fi