CREATE SCHEMA IF NOT EXISTS strabospot;

CREATE TABLE IF NOT EXISTS strabospot.featured_spots (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  spot_id integer UNIQUE NOT NULL,
  geom GEOMETRY(Point, 4326) NOT NULL,
  symbol text,
  data jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_strabospot_featured_spots_geom ON strabospot.featured_spots USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_strabospot_featured_spots_spot_id ON strabospot.featured_spots (spot_id);
