#!/usr/bin/env bash

# Use the project-level virtualenv
export PATH=$PWD/.venv/bin:$PATH
# ...instead of subproject virtualenvs
export POETRY_VIRTUALENVS_CREATE=false

cd tools/macrostrat-integration

poetry lock --no-update
poetry install