#!/usr/bin/env zsh
# Description: transfer a file to an AWS bucket
# Usage: strat s3-transfer <file> <bucket>

# Grab config from .env
set -o allexport
source "$STRAT_BASE/chtc/.env"
set +o allexport

aws s3 cp --endpoint $AWS_ENDPOINT $1 s3://$2
