#!/usr/bin/env bash

cd $STRAT_BASE/services/macrostrat-api

registry_address="$MACROSTRAT_PRIVATE_REGISTRY"
container_name="macrostrat/api"
version="develop"
# Log into local docker registry
#docker login $registry_address

docker build -t $container_name:$version .

# Tag the image
docker tag $container_name:$version $registry_address/$container_name:$version

# Push the image
docker push $registry_address/$container_name:$version