#!/usr/bin/env zsh

### Dumps the macrostrat schema from burwell and restores it
## to column_data, the database referenced for dacite 2.0
## then run database alterations (i.e primary keys)


########################## functions #################################
help()
{
   echo  
   echo "Script to dump postgres instance of macrostrat schema from gunnison"
   echo "WARNING: this will first drop the database specified in -d"
   echo 
   echo "Syntax: scriptTemplate [ -p | -c | -d | -U | -h, --help]"
   echo "options:"
   echo "-p            Port that gunnison is explosed to on your localhost, default 54381"
   echo "-c            Container name of db sql is being performed. Default db"
   echo "-d            Name of db in cluster. Default column_data"
   echo "-U            Name of db user. Default postgres"
   echo "-h, --help    Display help"
   echo
}

check()
{
    echo "Gathering arguments"
    while getopts ":c:d:U:h" opt; do
        case $opt in 
            c) container_name=$OPTARG;;
            d) alter_db=$OPTARG;;
            U) db_user=$OPTARG;;
            h) help; exit 1 ;; 
           \?) help; exit 1 ;; 
        esac
    done
}
############################ variables ################################

dbname=burwell
alter_db=column_data
container_name=postgres
db_user=postgres

########################### main script ###############################
check $@

export $(grep -v '^#' .env | xargs)

strat compose exec $container_name psql -c "DROP DATABASE $alter_db WITH (FORCE);"
strat compose exec $container_name createdb -U$db_user $alter_db

echo "Running Pre-dump sql scripts"
for file in `dirname $0`/../sql/pre-runs/*.sql
do
    `dirname $0`/./run-sql-file -f $file -c $container_name -d $alter_db -U $db_user
done

echo "Dumping Burwell Macrostrat schema to $alter_db"
strat compose exec $container_name psql -U$db_user $alter_db -c "CREATE EXTENSION postgis;"
strat compose exec pg_dump -Fc -U postgres \
  --schema=macrostrat \
  --exclude-table-data=macrostrat.strat_name_footprints \
  --exclude-table-data=macrostrat.measures \
  --exclude-table-data=macrostrat.measuremeta \
  --exclude-table-data=macrostrat.lookup_unit_attrs_api \
  --exclude-table-data=macrostrat.pbdb_collections \
  $dbname \
| strat compose exec -T $container_name pg_restore -v -U$db_user -d $alter_db


for file in `dirname $0`/../sql/db-alterations/*.sql
do
    cat $file | strat compose exec -T postgres psql -Upostgres $alter_db
done
for f in `dirname $0`/../../api-views/*.sql
do
    cat $f | strat compose exec -T postgres psql -Upostgres $alter_db
done
