GET https://dev2.macrostrat.org/api/pg/rpc/auth_status
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwLTAwMDMtMTg5NS0zNzQyIiwicm9sZSI6IndlYl9hZG1pbiIsImdyb3VwcyI6WzFdLCJncm91cF9uYW1lcyI6WyJhZG1pbiJdLCJleHAiOjE3MjkxNTk3ODR9.wzuW_RGl-Qs_y2qS9eHAxIoQA-kQ_OsSV6A1gXr6BAg"

