name: Build legacy tileserver
on:
  push:
    branches: ["main"]
    paths:
      - py-modules/tileserver-utils/**
      - services/legacy-tileserver/**
      - scripts/service-release
      - .github/workflows/build-service.yaml
      - .github/workflows/build-legacy-tileserver.yaml
  pull_request:
    branches: ["main"]
    paths:
      - py-modules/tileserver-utils/**
      - services/legacy-tileserver/**
      - scripts/service-release
      - .github/workflows/build-service.yaml
      - .github/workflows/build-legacy-tileserver.yaml
jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build-service.yaml
    with:
      service: legacy-tileserver
      image: legacy-tileserver
      context: services/legacy-tileserver
      build-contexts: py-modules=./py-modules
    secrets: inherit
