name: Build Celery worker
on:
  push:
    branches: ["main"]
    paths:
      - py-modules/map-utils/**
      - py-modules/column-ingestion/**
      - py-modules/column-utils/**
      - py-modules/core/**
      - services/worker/**
      - scripts/service-release
      - .github/workflows/build-service.yaml
      - .github/workflows/build-worker.yaml
  pull_request:
    branches: ["main"]
    paths:
      - py-modules/map-utils/**
      - py-modules/column-ingestion/**
      - py-modules/column-utils/**
      - py-modules/core/**
      - services/worker/**
      - scripts/service-release
      - .github/workflows/build-service.yaml
      - .github/workflows/build-worker.yaml
jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build-service.yaml
    with:
      service: worker
      image: worker
      context: services/worker
      build-contexts: |
        py-modules=./py-modules
        submodules=./submodules
    secrets: inherit
