name: Build tileserver
on:
  push:
    branches: ["main"]
    paths:
      - py-modules/tileserver-utils/**
      - py-modules/map-utils/**
      - services/tileserver/**
      - scripts/service-release
      - .github/workflows/build-service.yaml
      - .github/workflows/build-tileserver.yaml
  pull_request:
    branches: ["main"]
    paths:
      - py-modules/tileserver-utils/**
      - py-modules/map-utils/**
      - services/tileserver/**
      - scripts/service-release
      - .github/workflows/build-service.yaml
      - .github/workflows/build-tileserver.yaml
jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build-service.yaml
    with:
      service: tileserver
      image: tileserver
      context: services/tileserver
      build-contexts: py-modules=./py-modules
    secrets: inherit
