name: Build API v3
on:
  push:
    branches: ["main"]
    paths:
      - py-modules/column-utils/**
      - py-modules/map-utils/**
      - py-modules/map-topology/**
      - py-modules/match-utils/**
      - services/api-v3/**
      - scripts/service-release
      - .github/workflows/build-service.yaml
      - .github/workflows/build-api-v3.yaml
  pull_request:
    branches: ["main"]
    paths:
      - py-modules/column-utils/**
      - py-modules/map-utils/**
      - py-modules/map-topology/**
      - py-modules/match-utils/**
      - services/api-v3/**
      - scripts/service-release
      - .github/workflows/build-service.yaml
      - .github/workflows/build-api-v3.yaml
jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/build-service.yaml
    with:
      service: api-v3
      image: api-v3
      context: services/api-v3
      build-contexts: py-modules=./py-modules
    secrets: inherit
