name: Macrostrat continuous integration testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Install poetry and fix setuptools error
      - name: Install poetry
        run: pipx install poetry

      # External GDAL is needed for map integration system installation now.
      # We might try to remove this in the future, or figure out how to use
      # a bundled version of GDAL from the virtual environment.
      - name: Install GDAL
        run: |
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Run Macrostrat tests
        run: make test-ci
